//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmSitesi.Resources {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmSitesi.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Abone Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AboneOl {
            get {
                return ResourceManager.GetString("AboneOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Filmler için haber almak isterseniz mail adresinizi yazınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string AltMesaj {
            get {
                return ResourceManager.GetString("AltMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Arama {
            get {
                return ResourceManager.GetString("Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bize Ulaşın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string BizeUlasin {
            get {
                return ResourceManager.GetString("BizeUlasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   destek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string destek {
            get {
                return ResourceManager.GetString("destek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En iyi Filmler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EniyiFilmler {
            get {
                return ResourceManager.GetString("EniyiFilmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film Bilgi Sistemi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FilmBilgiSistemi {
            get {
                return ResourceManager.GetString("FilmBilgiSistemi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GÖNDER benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Gönder {
            get {
                return ResourceManager.GetString("Gönder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Görsellik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Gorsellik {
            get {
                return ResourceManager.GetString("Gorsellik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncel benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Guncel {
            get {
                return ResourceManager.GetString("Guncel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncel Filmler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string GüncelFilm {
            get {
                return ResourceManager.GetString("GüncelFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkımızda benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Film bilgi sistemi web sitemizden en güncel, en yeni, yüksek kaliteli filmleri izleyebilir ve hakkında bilgi sahibi olabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HakkımızdaMesaj {
            get {
                return ResourceManager.GetString("HakkımızdaMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hedefler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hedefler {
            get {
                return ResourceManager.GetString("Hedefler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hepsi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Hepsi {
            get {
                return ResourceManager.GetString("Hepsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En Güncel Film Bilgi Sistemine Hoşgeldiniz! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HosGeldinMesaji1 {
            get {
                return ResourceManager.GetString("HosGeldinMesaji1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncel film bilgilerini takip etmek isterseniz sitemizi ziyaret ediniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string HosGeldinMesaji2 {
            get {
                return ResourceManager.GetString("HosGeldinMesaji2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string İletisim {
            get {
                return ResourceManager.GetString("İletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Iletişim Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IletisimBilgileri {
            get {
                return ResourceManager.GetString("IletisimBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Istek ve önerileriniz için lütfen yazınız... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IletisimMesaj {
            get {
                return ResourceManager.GetString("IletisimMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İzlenilen benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Izlenilen {
            get {
                return ResourceManager.GetString("Izlenilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kategoriler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesaj benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MESAJINIZI YAZINIZ... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string MesajYaz {
            get {
                return ResourceManager.GetString("MesajYaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misyonumuz benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Misyonumuz {
            get {
                return ResourceManager.GetString("Misyonumuz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Soyad {
            get {
                return ResourceManager.GetString("Soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Strateji Çözümleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StratejiCozumleri {
            get {
                return ResourceManager.GetString("StratejiCozumleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please write for your requests and suggestions ... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tarihçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Tarihce {
            get {
                return ResourceManager.GetString("Tarihce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telif Hakkı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Telifhakkı {
            get {
                return ResourceManager.GetString("Telifhakkı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temiz Modern Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string TemizKod {
            get {
                return ResourceManager.GetString("TemizKod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Filmler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YeniFilmler {
            get {
                return ResourceManager.GetString("YeniFilmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yenilikçilik benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Yenilikcilik {
            get {
                return ResourceManager.GetString("Yenilikcilik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   En popüler Filmler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string YüksekKaliteFilm {
            get {
                return ResourceManager.GetString("YüksekKaliteFilm", resourceCulture);
            }
        }
    }
}
